# Test building
import sys
import os
import darwin


largeFileFlags = '-DHAVE_LARGEFILE_SUPPORT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE'
env = Environment(CCFLAGS    = '-O2 -Wall -m32 ' + largeFileFlags,)

print env["ENV"]
#print env.Dump()
darwin.darwincompile(env)
print env["ENV"]

env.Program(target='test', source=['test.c','output.f'])

