# Test building
import sys
import os
Import ('OSXCC OSXsysroot')

platform = sys.platform

largeFileFlags = '-DHAVE_LARGEFILE_SUPPORT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE'
env = Environment(CCFLAGS    = '-O2 -Wall -m32 ' + largeFileFlags,)
env.PrependENVPath('PATH', '/vnmr/gcc/bin')

print env["ENV"]

if (platform == 'darwin'):
      env.Replace(CC=OSXCC)

if (OSXsysroot and (OSXCC == 'gcc')):
  env.Append(CPPDEFINES = 'MACOS', CPPFLAGS = ' -arch i386 -isysroot '+OSXsysroot,
        LINKFLAGS = ' -arch i386 -L/usr/lib', FORTRANFLAGS = ' -m32 ')
else:
  env.Append(CPPDEFINES = 'MACOS', CPPFLAGS = ' -arch i386 ',
        LINKFLAGS = ' -arch i386 -L/usr/lib ', FORTRANFLAGS = ' -m32 ')

env.Replace(FORTRAN='gfortran')
env.Program(target='test', source=['test.c','output.f'])

